version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - link_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - link_network

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222" # 클라이언트 연결 포트
      - "8222:8222" # 모니터링 포트
    networks:
      - link_network

  nats_jetstream:
    image: nats:latest
    container_name: nats_jetstream
    command: ["-js"] # JetStream 활성화 옵션
    ports:
      - "4223:4222" # 클라이언트 연결 포트
      - "8223:8222" # 모니터링 포트
    networks:
      - link_network

  golang_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang_app
    depends_on:
      - postgres
      - redis
      - mongo
      - nats
      - nats_jetstream
    environment:
      GO_ENV: ${GO_ENV}
      PORT: ${HTTP_PORT}
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      POSTGRES_DSN: ${POSTGRES_DSN}
      SYSTEM_ADMIN_EMAIL: ${SYSTEM_ADMIN_EMAIL}
      SYSTEM_ADMIN_PASSWORD: ${SYSTEM_ADMIN_PASSWORD}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      MONGO_DSN: ${MONGO_DSN}
      DEFAULT_PROFILE_IMAGE_URL: ${DEFAULT_PROFILE_IMAGE_URL}
      NATS_URL: ${NATS_URL} # NATS 연결 주소
      NATS_JETSTREAM_URL: ${NATS_JETSTREAM_URL} # NATS JetStream 연결 주소
    volumes:
      - .:/app
    ports:
      - "${HTTP_PORT}:8080"
    command: ["air", "-c", "/app/.air.toml"]
    networks:
      - link_network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - link_network

volumes:
  postgres_data:
  redis_data:
  mongo_data:

networks:
  link_network:
    driver: bridge
