apiVersion: apps/v1
kind: Deployment
metadata:
  name: link
spec:
  replicas: 1  # 복제본 수 설정
  selector:
    matchLabels:
      app: link
  template:
    metadata:
      labels:
        app: link
    spec:
      containers:
        - name: link-api
          image: your-docker-image # Docker 이미지 이름과 태그로 변경 필요
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: link-service
spec:
  type: NodePort
  selector:
    app: link
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # NodePort는 보통 30000-32767 사이에서 선택해야 함
